- hosts: k8s-master
  become: yes
  user: ubuntu
  gather_facts: no
  pre_tasks:
  - name: 'Atualzando o repo'
    raw: 'apt update'
  - name: 'Instalando o python'
    raw: 'apt install -y python'
  roles:
  - { role: install-k8s, tags: ["install_k8s_role"] }

- hosts: k8s-master
  become: yes
  user: ubuntu
  roles:
  - { role: create-cluster, tags: ["create_clusteer_role"] }

- hosts: k8s-workers
  become: yes
  user: ubuntu
  roles:
  - { role: join-workers, tags: ["join_workers_role"] }

