- name: 
  debug:
    msg: "[MASTER] K8S_TOKEN_HOLDER -O token eh {{ hostvars['K8S_TOKEN_HOLDER']['token'] }}"

- name: 
  debug:
    msg: "[MASTER] K8S_TOKEN_HOLDER -O hash eh {{ hostvars['K8S_TOKEN_HOLDER']['hash'] }}"

- name: Removendo o cluster
  command: 
    kubeadm reset --force
  register: kubeadm_reset

#https://github.com/containerd/containerd/issues/4581
- name: Removendo config.toml
  shell: rm -Rf /etc/containerd/config.toml || true

- name: Restartando service containerd
  ansible.builtin.service:
    name: containerd
    state: restarted  

- name: Adicionando o worker ao cluster k8s
  shell: 
    kubeadm join --token={{ hostvars['K8S_TOKEN_HOLDER']['token'] }} 
    --discovery-token-ca-cert-hash sha256:{{ hostvars['K8S_TOKEN_HOLDER']['hash'] }} 
    {{K8S_MASTER_NODE_IP}}:{{K8S_API_SECURE_PORT}}



